import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Bricolage_Grotesque } from "next/font/google";

const bricolage = Bricolage_Grotesque( {
  subsets: [ "latin" ],
  weight: [ "400", "700" ],
} );


const geistSans = Geist( {
  variable: "--font-geist-sans",
  subsets: [ "latin" ],
} );

const geistMono = Geist_Mono( {
  variable: "--font-geist-mono",
  subsets: [ "latin" ],
} );

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout ( { children } ) {
  return (
    <html lang="en">
      <body
        className={ `${ geistSans.variable } ${ geistMono.variable } antialiased ${ bricolage.className }` }
      >
        { children }
      </body>
    </html>
  );
}
